language: go
go:
  - 1.3
  - 1.4
  - tip
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libssh2-1-dev openssh-client openssh-server
 - git clone https://github.com/libgit2/libgit2.git /tmp/libgit2
 - mkdir /tmp/libgit2/build
 - pushd /tmp/libgit2/build
 - cmake -DBUILD_CLAR=OFF DCMAKE_C_FLAGS=-fPIC ..
 - sudo cmake --build . --target install
 - popd
script:
  - go build -x ./...
  - go test -v ./...
