language: go
go:
  - 1.3
  - 1.4
  - tip
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libssh2-1-dev openssh-client openssh-server
 - cd /tmp
 - git clone https://github.com/libgit2/libgit2.git
 - mkdir libgit2/build
 - cd libgit2/build
 - cmake -DBUILD_CLAR=OFF ..
 - sudo cmake --build . --target install
script:
  - go test -v ./...
